# Generated by Django 5.1.3 on 2024-12-03 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
